name: C/C++ CI

on:
  push:
    branches: [ "orange-pi-6.1-sun50iw9" ]
  pull_request:
    branches: [ "orange-pi-6.1-sun50iw9" ]

jobs:
  build:

    runs-on: ubuntu:latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: make defconfig
    - name: make
      run: make
